name: Latest Build

on:
   push:
      branches: [ master ]
   pull_request:
      branches: [ master ]

jobs:
   build:
      strategy:
         fail-fast: false
         matrix:
            jdk: [8, 11, 17, 20, 21]

      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v6
         
         - name: Set up JDK ${{ matrix.jdk }}
           uses: actions/setup-java@v5
           with:
               distribution: 'temurin'
               java-version: ${{ matrix.jdk }}

         - name: Validate Gradle wrapper
           uses: gradle/actions/wrapper-validation@v6

         - name: Make gradlew executable
           run: chmod +x ./gradlew

         - name: Build with Gradle
           run: ./gradlew build
