name: Unit Tests

on:
   pull_request:
      branches: [ master ]

jobs:
   build:
      name: Unit Tests
      runs-on: ubuntu-latest
      steps:
      -  uses: actions/checkout@v2
         with:
            fetch-depth: 0
            
      -  name: Set up JDK 11
         uses: actions/setup-java@v3
         with:
            distribution: temurin
            java-version: 11
            cache: gradle
            
      -  name: Make gradlew executable
         run: chmod +x ./gradlew
      -  name: Build and Test
         env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: ./gradlew generateTestSource test jacocoTestReport --info -Dfull_test_suite=true
         
      -  name: Publish Test Result
         uses: EnricoMi/publish-unit-test-result-action@v1
         id: test-results
         if: always()
         with:
            files: build/test-results/**/*.xml
            fail_on: nothing
            ignore_runs: true
            json_thousands_separator: .
            time_unit: milliseconds