name: Sync Branch

on:
   push:
      branches: [ master ]
      
jobs:
   build:
      name: Sync Branch
      runs-on: ubuntu-latest
      steps:
      -  uses: actions/checkout@v2
         with:
            fetch-depth: 0
            
      -  name: Set up JDK 11
         uses: actions/setup-java@v3
         with:
            distribution: temurin
            java-version: 11
            cache: gradle
            
      -  name: Make gradlew executable
         run: chmod +x ./gradlew
      -  name: Build and Test
         run: ./gradlew generateGithubSource --info -Dfull_test_suite=true
         
      - uses: GuillaumeFalourd/copy-push-files@v1
        with:
          source_files: src Changelog.md README.md
          remote_repository: https://github.com/Speiger/Primitive-Collections
          access_token: ${{ secrets.PUSH_TOKEN }}
          target_branch: debug
          